import React, { ImgHTMLAttributes, useState, useEffect } from 'react';

interface ImageProps extends Omit<ImgHTMLAttributes<HTMLImageElement>, 'src' | 'alt'> {
  src: string;
  alt: string;
  width?: number | string;
  height?: number | string;
  loading?: 'eager' | 'lazy';
  decoding?: 'async' | 'auto' | 'sync';
}

let webpSupported: boolean | null = null;

const checkWebPSupport = (): boolean => {
  if (typeof window === 'undefined') return false; // SSR
  if (webpSupported !== null) return webpSupported;
  
  const canvas = document.createElement('canvas');
  if (canvas.toDataURL) {
    webpSupported = canvas.toDataURL('image/webp').indexOf('data:image/webp') === 0;
  } else {
    webpSupported = false;
  }
  return webpSupported;
};

export const OptimizedImage: React.FC<ImageProps> = ({
  src,
  alt,
  className = '',
  width,
  height,
  loading = 'lazy',
  decoding = 'async',
  style = {},
  ...props
}) => {
  const [currentSrc, setCurrentSrc] = useState<string>(src);
  const [hasError, setHasError] = useState(false);
  
  // Determine the optimal source URL
  useEffect(() => {
    if (typeof window === 'undefined') return;
    
    const isWebPSupported = checkWebPSupport();
    const isExternal = src.startsWith('http');
    const alreadyWebP = src.endsWith('.webp');
    
    if (!isWebPSupported || isExternal || alreadyWebP) {
      setCurrentSrc(src);
      return;
    }
    
    // Try to use WebP version
    const webpSrc = src.replace(/\.(jpg|jpeg|png)$/i, '.webp');
    // If same as src, no extension matched
    if (webpSrc === src) {
      setCurrentSrc(src);
      return;
    }
    
    // We assume WebP file exists (generated by scripts/generate-webp.js)
    setCurrentSrc(webpSrc);
  }, [src]);
  
  const handleError = () => {
    if (!hasError && currentSrc !== src) {
      // Fallback to original source
      setCurrentSrc(src);
      setHasError(true);
    }
  };

  const imgStyle: React.CSSProperties = {
    ...style,
    width: width ? (typeof width === 'number' ? `${width}px` : width) : '100%',
    height: height ? (typeof height === 'number' ? `${height}px` : height) : 'auto',
  };

  const imgProps: ImgHTMLAttributes<HTMLImageElement> = {
    src: currentSrc,
    alt,
    className,
    width: typeof width === 'number' ? width : undefined,
    height: typeof height === 'number' ? height : undefined,
    loading,
    decoding,
    style: imgStyle,
    onError: handleError,
    ...props
  };

  return React.createElement('img', imgProps);
};

// Extend Vite's import.meta type
declare global {
  interface ImportMeta {
    env: {
      DEV: boolean;
    };
  }
}

export const getOptimizedImageUrl = (src: string): string => {
  // In development, return the original src
  if (import.meta.env.DEV) return src;
  
  // In production, Vite will handle the optimization
  // This assumes you're using Vite's asset handling
  return new URL(`/src/assets/${src}`, import.meta.url).href;
};

